# Informations sur le site
site_name: NWS Laser Documentations
site_url: https://doc.nwslaser.fr/

# Thème et apparence
theme:
  name: material
  language: fr
  logo: assets/nws_laser_tr.png
  favicon: assets/nws_laser_tr.png
  palette:
    # Palette de couleurs
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Passer au mode sombre
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passer au mode clair

# Navigation (vous ajouterez vos pages ici )
nav:
  - 'Accueil': index.md
  - 'Nos Gammes':
    - 'LaserKube':
      - 'LaserKube-X': laserkube/laserkube-x.md
      - 'LaserKube-MAX': laserkube/laserkube-max.md
      - 'LaserKube-MAX UV': laserkube/laserkube-max-uv.md
    - 'IK-Series':
      - 'IK-Series M20': ik-series/ik-series-m20.md
      - 'IK-Series UV5': ik-series/ik-series-uv5.md
      - 'IK-Series CODUO': ik-series/ik-series-coduo.md
    - 'IK-BOX': ik-box/index.md
    - 'CUT-M': cut-m/index.md
    - 'CUT-X PRO': cut-x-pro/index.md
  - 'Page d attente type': en-construction.md # Utile pour le développement

# Extensions Markdown (recommandé de les ajouter si elles n'y sont pas)
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
