# Informations sur le site
site_name: NWS Laser Documentations
site_url: https://doc.nwslaser.fr/

# Thème et apparence
theme:
  name: material
  language: fr
  logo: assets/nws_laser_tr.png
  favicon: assets/nws_laser_tr.png
  palette:
    # Palette pour le mode clair
    - scheme: default
      primary: custom  # <-- On utilise 'custom' car ce n'est pas une couleur standard
      accent: indigo   # <-- L'accent est pour les éléments interactifs (boutons, etc.)
      toggle:
        icon: material/weather-sunny
        name: Passer au mode sombre

    # Palette pour le mode sombre
    - scheme: slate
      primary: custom  # <-- On peut aussi l'utiliser pour le mode sombre
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passer au mode clair
  
# Navigation (vous ajouterez vos pages ici )
nav:
  - 'Accueil': index.md
  - 'Nos Gammes':
    - 'LaserKube':
      - 'LaserKube-X':
        - 'Guide de démarrage rapide': LaserKube/LaserKube-X/guide-demarrage-rapide_LK.md
        - 'Notice complète': LaserKube/LaserKube-X/notice-complete_LK.md
      - 'LaserKube-Max': LaserKube/LaserKube-Max/index.md
      - 'LaserKube-Max-UV': LaserKube/LaserKube-Max-UV/index.md

    - 'IK-Series':
      - 'IK-Series CODUO': IK-Series/ik-series-coduo.md
      - 'IK-Series M20': IK-Series/ik-series-m20.md
      - 'IK-Series UV5': IK-Series/ik-series-uv5.md

    - 'IK-Box': IK-Box/index.md
    - 'Cut-M': Cut-M/index.md
    - 'Cut-X-Pro': Cut-X-Pro/index.md

  - 'Page en construction': en-construction.md
# Extensions Markdown (recommandé de les ajouter si elles n'y sont pas)

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  # Permet les blocs d'avertissement comme !!! note
  - admonition
  # Permet d'ajouter des attributs HTML comme { width="..." }
  - attr_list
  # Permet d'interpréter le Markdown à l'intérieur de balises HTML (crucial pour les cartes)
  - md_in_html
  # Améliorations diverses pour la coloration du code, les listes, etc.
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


# ===================================================================
