# Informations sur le site
site_name: NWS Laser Documentations
site_url: https://doc.nwslaser.fr/

# ThÃ¨me et apparence
theme:
  name: material
  language: fr
  logo: assets/nws_laser_tr.png
  favicon: assets/nws_laser_tr.png
  
  palette:
    - scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Passer au mode sombre
    - scheme: slate
      primary: custom
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passer au mode clair
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    #- navigation.sections  # Sections pliables dans le menu latÃ©ral
    #- navigation.expand    # DÃ©veloppe automatiquement les sections
    #- navigation.top       # Bouton retour en haut
    #- toc.follow          # La TOC suit le scroll
    #- toc.integrate       # IntÃ¨gre la TOC dans la navigation
    - search.highlight
    - search.share
    - search.suggest

# ðŸ‘‰ EXTRA DOIT ÃŠTRE AU MÃŠME NIVEAU QUE theme/nav
extra:
  admonition:
    laser:
      name: Attention Laser
      icon: assets/icons/danger_laser.png
      color: "#d81b60"
  social:
    - icon: material/web
      link: https://nwslaser.fr
      name: Site NWS Laser

# Navigation
nav:
  - 'Accueil': index.md
  - 'Nos machines':
    - 'LaserKube':
      - 'LaserKube-X':
        - 'Guide de dÃ©marrage rapide': LaserKube/LaserKube-X/guide-demarrage-rapide_LK.md
        - 'Notice complÃ¨te': LaserKube/LaserKube-X/notice-complete_LK.md
      - 'LaserKube-Max': LaserKube/LaserKube-Max/index.md
      - 'LaserKube-Max-UV': LaserKube/LaserKube-Max-UV/index.md
    - 'IK-Series':
      - 'IK-Series CODUO': IK-Series/ik-series-coduo.md
      - 'IK-Series F20': IK-Series/ik-series-f20.md
      - 'IK-Series UV5': IK-Series/ik-series-uv5.md
    - 'IK-Box': IK-Box/index.md
    - 'Cut-M': Cut-M/index.md
    - 'Cut-X-Pro': Cut-X-Pro/index.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg